/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:e9f39839-dade-47c7-b77e-55944e467329",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_P8FEXhs80",
    "aws_user_pools_web_client_id": "7d1lfllun1tl13dve4lhcrppna",
    "oauth": {}
};


export default awsmobile;
